# Generated by Django 5.1.4 on 2024-12-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frequent_questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order", "title"], "verbose_name": "Question", "verbose_name_plural": "Questions"},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["order", "title"], "verbose_name": "Section", "verbose_name_plural": "Sections"},
        ),
    ]
