# Generated by Django 5.2.12 on 2026-03-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequent_questions', '0002_alter_question_options_alter_section_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order', 'title'), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order', 'title'), 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
    ]
