name: redirect_prod

services:

  webapp:
    extends:
      file: docker-compose.base.yml
      service: redirect_base
    container_name: redirect_prod
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile
    volumes:
      - ./backend/media:/var/www/redirect/backend/media
    environment:
      - "ENVIRONMENT=production"
    ports:
      - "${WEBAPP_PORT:-8080}:80"
    depends_on:
      - db

  db:
    extends:
      file: docker-compose.base.yml
      service: db_base_psql
    container_name: redirect_psql

volumes:
  redirect_psql:
