ARG NODE_VERSION=20.18.0

FROM node:${NODE_VERSION}-bookworm-slim

ENV PYTHONUNBUFFERED=1

ENV DEBUG=${DEBUG:-True}
ENV ENVIRONMENT=${ENVIRONMENT:-development}
ENV LOG_LEVEL=${LOG_LEVEL:-WARNING}

ENV RUN_MIGRATIONS=True
ENV RUN_COMPILE_MESSAGES=True
ENV RUN_COLLECT_STATIC=False
ENV RUN_CREATE_SUPER_USER=True
ENV RUN_SEED_GROUPS=True

ENV IS_CONTAINERIZED=True

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    nginx gcc xz-utils gettext python3 python3-pip python3-venv python3-dev git postgresql-client libpq-dev && \
    apt-get clean


ARG S6_OVERLAY_VERSION=3.2.0.0
ENV S6_CMD_WAIT_FOR_SERVICES_MAXTIME 0

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz && \
    tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz


COPY docker/nginx/nginx.conf /etc/nginx/sites-available/default
COPY docker/s6-rc.d /etc/s6-overlay/s6-rc.d


# Python virtualenv paths
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /var/www/redirect/backend/

# install the backend libraries:
COPY ./backend/pyproject.toml ./backend/requirements-dev.txt /var/www/redirect/backend/
RUN python3 -m pip install --upgrade pip setuptools && \
    python3 -m pip install -r ./requirements-dev.txt

# install the frontend libraries:
COPY ./backend/package.json ./backend/bower.json /var/www/redirect/backend/
RUN npm install -g npm bower && \
    bower install --allow-root --config.interactive=false

# copy the backend source code:
COPY ./backend/ /var/www/redirect/backend/
RUN rm -rf ./_appengine_legacy

USER root


# Make sure scripts in .local are usable:
ENV PATH=/root/.local/bin:$PATH

ARG VERSION
ARG REVISION
ENV VERSION=${VERSION}
ENV REVISION=${REVISION}

RUN touch /var/www/redirect/.version && \
    echo "$VERSION+$(echo ${REVISION} | cut -c 1-7)" > /var/www/redirect/.version

WORKDIR /var/www/redirect/

ENTRYPOINT ["/init"]

EXPOSE 8000
