import random
from typing import Any

from django.contrib.auth import get_user_model
from django.core.management import BaseCommand
from django.db import IntegrityError
from faker import Faker
from localflavor.ro.ro_counties import COUNTIES_CHOICES

from donations.models.ngos import Cause, Ngo
from utils.text.cleanup import clean_slug, strip_accents

fake = Faker("ro_RO")

# Disclaimer: The names and data here were generated with an LLM for the sole purpose of testing and having the ability
# to generate a plethora of random NGO names. Any resemblance to real organizations, living or dead, is purely
# coincidental and unintentional. Some names and combinations might be nonsensical or inappropriate; they were not
# curated for meaning or context. If you find any issues, please report them or create a PR so they can be addressed.
MOCK_NGO_NAMES = {
    "types": [
        "Alianța",
        "Asociația",
        "Federația",
        "Fundația",
        "Inițiativa",
        "Organizația",
        "Rețeaua",
        "Uniunea",
        "",
    ],
    "prefixes": [
        "Acces",
        "Acțiune",
        "Ajutor",
        "Ajută",
        "Artă",
        "Asistență",
        "Casa",
        "Copiii",
        "Cărțile",
        "Drepturile",
        "Educație",
        "Grija",
        "Hrana",
        "Incluziune",
        "Inițiativa",
        "Lupta",
        "ONG-ul",
        "Oameni",
        "Ochi",
        "Prietenii",
        "Promovarea",
        "Protecția",
        "Pădurea",
        "Salvarea",
        "Salvați",
        "Solidaritate",
        "Speranța",
        "Speranță",
        "Sprijin",
        "Sprijină",
        "Sănătate",
        "Viitor",
        "Îmbunătățirea",
        "Împreună",
        "Înfruntă",
        "Îngrijire",
        "Învinge",
    ],
    "focus_areas": [
        "Abilități Sociale",
        "Acces Medical",
        "Acces pentru Toți",
        "Accesibilitate",
        "Ajutor Umanitar",
        "Ajutor pentru Boli Rare",
        "Ajutor pentru Refugiați",
        "Ajutor pentru Satele Izolate",
        "Alfabetizare",
        "Ambiente Protejate",
        "Analiza Politicilor",
        "Animalelor Sălbatice",
        "Antidiscriminare",
        "Apa și Salubritate",
        "Apicultura",
        "Apropo de Viață",
        "Aprovizionare Durabilă",
        "Aprovizionare cu Energie",
        "Apă Potabilă",
        "Arii Protejate",
        "Arte Tradiționale",
        "Arte",
        "Artei Teatrale",
        "Artizanat și Meșteșuguri",
        "Asigurări Sociale",
        "Asistenți Sociali",
        "Asistenți Veterinari",
        "Autism",
        "Autobuz pentru Toți",
        "Autoconducere Comunității",
        "Autosuficiență",
        "Aventuri în Natură",
        "Aveți Nevoie de Ajutor",
        "Aviație Durabilă",
        "Avocați Drepturilor",
        "Bani și Finanțe",
        "Baza de Date",
        "Becuri Durabile",
        "Bere Ecologică",
        "Beton Durabil",
        "Bibliotecă",
        "Biciclete",
        "Biodiversitate",
        "Biofizica",
        "Biologie",
        "Biomedicină",
        "Birotică",
        "Blocuri de Beton",
        "Boli Cardiovasculare",
        "Boli Cronice",
        "Boli Genetice",
        "Boli Infecțioase",
        "Boli Intestinale",
        "Boli Mentale",
        "Boli Neurodegenerative",
        "Boli Oculare",
        "Boli Pielii",
        "Boli Psihice",
        "Boli Psihosomatice",
        "Boli Rare",
        "Boli Respiratorii",
        "Boli Reumatice",
        "Boli Sexuale",
        "Boli Transmisibile",
        "Boli Virale",
        "Bolnave de Sân",
        "Bolnave din Spital",
        "Bolnave",
        "Bolnavi Coreeni",
        "Bolnavi Cronici",
        "Bolnavi Fără Acces la Îngrijiri",
        "Bolnavi Fără Apă",
        "Bolnavi Infectați",
        "Bolnavi Pediatrici",
        "Bolnavi Psihiatrici",
        "Bolnavi Terminali",
        "Bolnavi Vechi",
        "Bolnavi Venerici",
        "Bolnavi cu Leucemie",
        "Bolnavi cu Parkinson",
        "Bolnavi de Alzheimer",
        "Bolnavi de Cancer",
        "Bolnavi din Comunități Marginalizate",
        "Bolnavii de SIDA",
        "Bolnavii de Sindrom Down",
        "Bolnavii de Tuberculoză",
        "Boții Asigurării",
        "Boții Electrice",
        "Boții Sociale",
        "Boții Tradiționale",
        "Brodării Tradiționale",
        "Brățară Medicală",
        "Bătrânețe",
        "Bătrânii Activi",
        "Bătrânii Singuri",
        "Bătrânii Vulnerabili",
        "Bătrânii",
        "Cadre Didactice",
        "Cadre Medicale",
        "Cadre Medii Vizibile",
        "Cadre Medii",
        "Cadre Sociale",
        "Cadre Speciale",
        "Cadre Studente",
        "Cadre Tinere",
        "Cadre Voluntare",
        "Cadru Didactic",
        "Cadru Igienic",
        "Cadru Legal",
        "Cadru Mediu Protejat",
        "Cadru Mediu Sustenabil",
        "Cadru Mediu Sănătos",
        "Cadru Mediu Urbain",
        "Cadru Mediu Vizibil",
        "Cadru Metodologic Complet",
        "Cadru Metodologic Detailat",
        "Cadru Metodologic Dezvoltat",
        "Cadru Metodologic Documentat",
        "Cadru Metodologic Dur",
        "Cadru Metodologic E-Learning",
        "Cadru Metodologic Educativ",
        "Cadru Metodologic Eficient",
        "Cadru Metodologic Evaluabil",
        "Cadru Metodologic Exemplar",
        "Cadru Metodologic Explicit",
        "Cadru Metodologic Fiabil",
        "Cadru Metodologic Flexibil",
        "Cadru Metodologic Gol",
        "Cadru Metodologic Riguros",
        "Cadru Metodologic Robust",
        "Cadru Metodologic Solid",
        "Cadru Metodologic Sustenabil",
        "Cadru Metodologic Testat",
        "Cadru Metodologic Transparent",
        "Cadru Metodologic Valid",
        "Cadru Metodologic Verificabil",
        "Cadru Metodologic Viabil",
        "Cadru Metodologic",
        "Cadru Pedagogic",
        "Cadru Reglator",
        "Cadru Social",
        "Cadru Spital",
        "Cadru Universitar",
        "Cadru Voluntar",
    ],
    "descriptors": [
        "Accesibil",
        "Accidental",
        "Acreditat",
        "Activ",
        "Acut",
        "Adaptabil",
        "Aditiv",
        "Agnostic",
        "Agrегat",
        "Antic",
        "Ascuns",
        "Asimilationist",
        "Ateu",
        "Autonomist",
        "Avansat",
        "Bazată pe Dovezi",
        "Calcificat",
        "Calificat",
        "Centralist",
        "Ceramizat",
        "Ceremonios",
        "Certificat",
        "Civic",
        "Coagulat",
        "Cognitiv",
        "Comic",
        "Compact",
        "Comportamental",
        "Comunitar",
        "Concentrat",
        "Condensat",
        "Confederat",
        "Conservator",
        "Constrânsor",
        "Contemporan",
        "Continuu",
        "Cosmopolit",
        "Cristalizat",
        "Critic",
        "Cronic",
        "Cronici",
        "Cuaternar",
        "Cyclic",
        "Deist",
        "Deliberat",
        "Dens",
        "Deschis",
        "Deplasat",
        "Dezorganizat",
        "Dezvoltat",
        "Diasporic",
        "Digitală",
        "Dinamic",
        "Disjunctiv",
        "Dispersat",
        "Dramatic",
        "Dualist",
        "Durabilă",
        "Echitabil",
        "Ecologică",
        "Eficace",
        "Eficient",
        "Egal",
        "Elastic",
        "Emancipatoare",
        "Emigrant",
        "Emoțional",
        "Epic",
        "Esențial",
        "Etic",
        "Evaluat",
        "Evaporat",
        "Evolutiv",
        "Exclusiv",
        "Expatriat",
        "Extractiv",
        "Extremist",
        "Federalist",
        "Flexibil",
        "Formal",
        "Fosil",
        "Funcționalist",
        "Futurist",
        "Globalist",
        "Haotic",
        "Holistică",
        "Immigrant",
        "Impermeabil",
        "Inactiv",
        "Inclusiv",
        "Incluziv",
        "Independentist",
        "Inechitabil",
        "Inegal",
        "Inerț",
        "Informal",
        "Inovatoare",
        "Instabil",
        "Integrativ",
        "Integrativă",
        "Intenționat",
        "Interactiv",
        "Internațional",
        "Invizibil",
        "Involuntar",
        "Irațional",
        "Ironic",
        "Itinerant",
        "Izolat",
        "Laicist",
        "Laten",
        "Liber",
        "Lichid",
        "Lipsit de Solemnitate",
        "Liric",
        "Localista",
        "Manifest",
        "Marginal",
        "Medical",
        "Medicale",
        "Migrator",
        "Migratori",
        "Mineralizat",
        "Mobil",
        "Mobili",
        "Moderat",
        "Moderno",
        "Monist",
        "Monitorizat",
        "Monoteist",
        "Multiplicativ",
        "Nationalist",
        "Național",
        "Nedezvoltat",
        "Neformal",
        "Neglijat",
        "Neoficial",
        "Neutru",
        "Nomad",
        "Nomazi",
        "Nostalgic",
        "Nou",
        "Obiectiv",
        "Oficial",
        "Paliativă",
        "Panenteist",
        "Panteist",
        "Partial",
        "Participativă",
        "Particularist",
        "Pasiv",
        "Patriot",
        "Periurban",
        "Permanent",
        "Permeabil",
        "Permisiv",
        "Pirolizat",
        "Plasmific",
        "Plastic",
        "Pluralist",
        "Postmodern",
        "Premeditat",
        "Premodern",
        "Preventivă",
        "Primar",
        "Primitiv",
        "Prioritar",
        "Prioritizat",
        "Proactiv",
        "Profan",
        "Profesionistă",
        "Progresiv",
        "Progresivă",
        "Prospectiv",
        "Protectoare",
        "Păstori",
        "Radical",
        "Rar",
        "Rațional",
        "Reabilitativă",
        "Reactiv",
        "Recidivist",
        "Reformist",
        "Refugiat",
        "Refugiați",
        "Regional",
        "Regionalist",
        "Reglat",
        "Relax",
        "Religios",
        "Rentabil",
        "Replicabil",
        "Responsabil",
        "Responsabilă",
        "Restrictiv",
        "Retrospectiv",
        "Revoluționar",
        "Rigid",
        "Rural",
        "Sacru",
        "Sarcastic",
        "Satiric",
        "Scalabil",
        "Secular",
        "Secundar",
        "Sedentari",
        "Selectiv",
        "Sensibil",
        "Sentimental",
        "Separatist",
        "Sezonier",
        "Solemn",
        "Solidară",
        "Spiritual",
        "Spontan",
        "Stabil",
        "Stabili",
        "Strict",
        "Structuralist",
        "Subdezvolt",
        "Subiectiv",
        "Sublimat",
        "Subtractiv",
        "Suplu",
        "Sustenabilă",
        "Temporal",
        "Temporar",
        "Terapeutică",
        "Tertiar",
        "Terțiar",
        "Tragic",
        "Transactiv",
        "Transferabil",
        "Transformatoare",
        "Transfrontalier",
        "Transparență",
        "Trilist",
        "Unitiv",
        "Universalist",
        "Urban",
        "Urgent",
        "Vechi",
        "Verde",
        "Vital",
        "Vitrifiat",
        "Vizibil",
        "Volatil",
        "Volubil",
        "Voluntar",
        "Vulnerabil",
        "Wellness",
        "pentru Toți Copiii",
        "pentru Toți",
        "Închis",
    ],
    "suffixes": [
        "pentru Absolutism",
        "pentru Accesibilitate",
        "pentru Activitate Civică",
        "pentru Acțiune Civică",
        "pentru Acțiune Industrială",
        "pentru Advocacy Civică",
        "pentru Advocacy",
        "pentru Advocația Sociala",
        "pentru Aer",
        "pentru Altruism",
        "pentru Anarhism",
        "pentru Angajament",
        "pentru Animalele Sălbatice",
        "pentru Antreprenoriat",
        "pentru Anxietate",
        "pentru Ape",
        "pentru Aristocrație",
        "pentru Arte",
        "pentru Asistență Psihosocială",
        "pentru Asociativism",
        "pentru Atingere",
        "pentru Auto-actualizare",
        "pentru Autoadministrare",
        "pentru Autocrație",
        "pentru Autodepășire",
        "pentru Autodeterminare",
        "pentru Autogestiune",
        "pentru Autolegislare",
        "pentru Autonomie Locală",
        "pentru Autonomie",
        "pentru Autorealizare",
        "pentru Autoritarism",
        "pentru Biodiversitate",
        "pentru Birocratic",
        "pentru Bună Guvernanță",
        "pentru Bunăstare Mental",
        "pentru Bunăstare",
        "pentru Burnout",
        "pentru Calificare",
        "pentru Caritate",
        "pentru Cetățenie",
        "pentru Coaching",
        "pentru Coeziune Socială",
        "pentru Colectivism",
        "pentru Compasiune",
        "pentru Compensație",
        "pentru Comunalism",
        "pentru Comunitarism",
        "pentru Comunitate",
        "pentru Conductă",
        "pentru Confederalism",
        "pentru Consiliere",
        "pentru Conversie Profesională",
        "pentru Cooperativism",
        "pentru Cultură",
        "pentru Decentralizare",
        "pentru Demnitate",
        "pentru Democratic",
        "pentru Democrație",
        "pentru Demonstrație",
        "pentru Depresia",
        "pentru Depășire",
        "pentru Despăgubire",
        "pentru Dezvoltare Economică",
        "pentru Dezvoltare Profesională",
        "pentru Dezvoltare",
        "pentru Dictatură",
        "pentru Digitalizare",
        "pentru Direcție",
        "pentru Direcționare",
        "pentru Dreptate Reparatorie",
        "pentru Dreptate",
        "pentru Dreptatea Civică",
        "pentru Dreptatea Penală",
        "pentru Dreptatea Sociale",
        "pentru Drepturile Consumatorului",
        "pentru Ecologie",
        "pentru Educație",
        "pentru Egalitarism",
        "pentru Egalitate",
        "pentru Eliberare",
        "pentru Emancipare",
        "pentru Empatie",
        "pentru Energii Regenerabile",
        "pentru Esgotament",
        "pentru Excelență",
        "pentru Excellence",
        "pentru Familialism",
        "pentru Federalism",
        "pentru Filantrropie",
        "pentru Formare Profesională",
        "pentru Ghidare",
        "pentru Grevă",
        "pentru Implicare Civică",
        "pentru Implicare",
        "pentru Incluziune Digitală",
        "pentru Incluziune",
        "pentru Independență",
        "pentru Inovație",
        "pentru Insurecție",
        "pentru Integrare",
        "pentru Istovire Emoțională",
        "pentru Justiție",
        "pentru Libertarism",
        "pentru Libertate",
        "pentru Locuri de Muncă",
        "pentru Matriarhalism",
        "pentru Mediu",
        "pentru Mentoring",
        "pentru Meritocratic",
        "pentru Meritocrație",
        "pentru Mobilitate Geografică",
        "pentru Mobilitate Profesională",
        "pentru Mobilitate Socială",
        "pentru Mobilitate de Carieră",
        "pentru Mobilizare",
        "pentru Mutualism",
        "pentru Natură",
        "pentru Oboseală",
        "pentru Ocupare",
        "pentru Oligarhie",
        "pentru Orientare",
        "pentru Pace",
        "pentru Participare",
        "pentru Patriarhalism",
        "pentru Performanță",
        "pentru Planeta",
        "pentru Plutocratic",
        "pentru Prevenția Bolilor Mental",
        "pentru Prevenția Conflictelor",
        "pentru Progres",
        "pentru Progresie de Carieră",
        "pentru Protecția Consumatorului",
        "pentru Protest",
        "pentru Păduri",
        "pentru Reabilitare Psihologică",
        "pentru Reabilitare Socială",
        "pentru Reabilitare",
        "pentru Realineere",
        "pentru Realizare",
        "pentru Recalibrare Etică",
        "pentru Recalibrare Morală",
        "pentru Recalibrare Spirituală",
        "pentru Recalibrare Valorică",
        "pentru Recalibrare",
        "pentru Reconciliere",
        "pentru Recuperare Economică",
        "pentru Recuperare Mentală",
        "pentru Recuperare",
        "pentru Redirecționare",
        "pentru Reintegrare",
        "pentru Reorientare",
        "pentru Reparație",
        "pentru Respectul Drepturilor",
        "pentru Responsabilitate",
        "pentru Restabilire",
        "pentru Restituire",
        "pentru Revenire",
        "pentru Revoltă",
        "pentru Revoluție",
        "pentru Rezoluție",
        "pentru Rezolvare",
        "pentru Schimbare Profundă",
        "pentru Schimbare",
        "pentru Scop",
        "pentru Securitate",
        "pentru Sens",
        "pentru Sindicate",
        "pentru Sol",
        "pentru Solidaritate",
        "pentru Soluție",
        "pentru Soluționarea Conflictelor",
        "pentru Speranță",
        "pentru Sport",
        "pentru Sprijin Emoțional",
        "pentru Sprijin Existențial",
        "pentru Sprijin Psihologic",
        "pentru Sprijin Spiritual",
        "pentru Stres",
        "pentru Sublimitate",
        "pentru Subsidiaritate",
        "pentru Succes",
        "pentru Suport Emoțional",
        "pentru Sustenabilitate",
        "pentru Sănătate Mental",
        "pentru Sănătate",
        "pentru Tehnologie Verde",
        "pentru Terapie",
        "pentru Tiranie",
        "pentru Totalitarism",
        "pentru Toți",
        "pentru Transcendență",
        "pentru Transformare Radicală",
        "pentru Transformare",
        "pentru Transparență",
        "pentru Viață",
        "pentru Viitor",
        "pentru Voi",
        "pentru Voluntariat",
        "pentru Împlinire",
    ],
    "inspirational": [
        "Aer",
        "Ape",
        "Apă",
        "Cai",
        "Ciclu",
        "Cosmos",
        "Cădere",
        "Cărări",
        "Devoluție",
        "Drumuri",
        "Eter",
        "Etern",
        "Evoluție",
        "Finit",
        "Flori",
        "Foc",
        "Frunze",
        "Galaxie",
        "Infinit",
        "Involuție",
        "Lumina",
        "Mică",
        "Noapte",
        "Orbită",
        "Orizont",
        "Poduri",
        "Pământ",
        "Revoluție",
        "Rotație",
        "Răchete",
        "Rădăcini",
        "Speranța",
        "Spirală",
        "Stea",
        "Temporal",
        "Univers",
        "Uriaș",
        "Vale",
        "Viața",
        "Viitor",
        "Vârf",
        "Zbor",
        "Ziua",
    ],
}


class Command(BaseCommand):
    help = "Generate fake Organizations for testing purposes"

    def add_arguments(self, parser):
        parser.add_argument(
            "total_orgs",
            type=int,
            help="How many organizations to create",
            default=10,
        )
        parser.add_argument(
            "--valid",
            action="store_true",
            help="Generate only valid, active organizations",
        )
        parser.add_argument(
            "--user_only",
            action="store_true",
            help="Generate only users with no organization",
        )

    def _generate_organization_name(self) -> str:
        """
        Generate a single random NGO name using various combinations.

        Returns:
            A single generated NGO organization name
        """
        strategies = [
            self._strategy_type_prefix_focus,
            self._strategy_prefix_focus_suffix,
            self._strategy_type_focus,
            self._strategy_simple_descriptive,
        ]

        strategy = random.choice(strategies)
        return strategy().strip().replace("  ", " ")

    def _strategy_type_prefix_focus(self) -> str:
        """Type + Prefix + Focus Area"""
        type_org = random.choice(MOCK_NGO_NAMES["types"])
        prefix = random.choice(MOCK_NGO_NAMES["prefixes"])
        focus = random.choice(MOCK_NGO_NAMES["focus_areas"])

        name = f"{type_org} {prefix} {focus}"
        return name

    def _strategy_prefix_focus_suffix(self) -> str:
        """Prefix + Focus + Suffix"""
        prefix = random.choice(MOCK_NGO_NAMES["prefixes"])
        focus = random.choice(MOCK_NGO_NAMES["focus_areas"])
        suffix = random.choice(MOCK_NGO_NAMES["suffixes"])

        name = f"{prefix} {focus} {suffix}"
        return name

    def _strategy_type_focus(self) -> str:
        """Type + Focus Area"""
        type_org = random.choice(MOCK_NGO_NAMES["types"])
        focus = random.choice(MOCK_NGO_NAMES["focus_areas"])

        name = f"{type_org} {focus}"
        return name

    def _strategy_simple_descriptive(self) -> str:
        """Simple: Prefix + Descriptor"""
        prefix = random.choice(MOCK_NGO_NAMES["prefixes"])
        descriptor = random.choice(MOCK_NGO_NAMES["descriptors"])

        name = f"{prefix} {descriptor}"
        return name

    def handle(self, *args, **options):
        total_organizations = options["total_orgs"]
        create_valid = options.get("valid", None)
        create_user_only = options.get("user_only", None)

        organizations: list[dict[str, Any]] = []
        generated_organization_names: list[str] = []

        user_model = get_user_model()

        self.stdout.write(self.style.SUCCESS(f"Generating {total_organizations} organization(s) to the database."))

        consecutive_creation_errors: int = 0
        consecutive_identical_names: int = 0
        while len(organizations) < total_organizations:
            county = COUNTIES_CHOICES[random.randint(0, len(COUNTIES_CHOICES) - 1)][1]
            address = fake.street_address()

            org_name: str = self._generate_organization_name()

            if org_name in generated_organization_names:
                consecutive_identical_names += 1
                if consecutive_identical_names > 5:
                    self.stdout.write(
                        self.style.ERROR("Too many consecutive identical names. Aborting and writing to the database.")
                    )
                    break
                continue

            consecutive_identical_names = 0
            generated_organization_names.append(org_name)

            kebab_case_name: str = clean_slug(strip_accents(org_name.lower()))

            first_name: str = fake.first_name()
            last_name: str = fake.last_name()

            email_domain: str = fake.domain_name()
            owner_email: str = f"{strip_accents(first_name.lower())}.{strip_accents(last_name.lower())}@{email_domain}"

            try:
                # noinspection PyArgumentList
                owner = user_model.objects.create_user(
                    email=owner_email,
                    password=owner_email.split("@")[0],
                    first_name=first_name,
                    last_name=last_name,
                    is_verified=random.choice([True, False]),
                )
                owner.save()
            except IntegrityError:
                continue

            should_not_have_ngo = random.choice(range(0, 6)) == 3
            if create_user_only or not create_valid and should_not_have_ngo:
                continue

            organization_details = {
                "name": org_name,
                "registration_number": fake.vat_id(),
                "address": address,
                "county": county,
                "active_region": county,
                "phone": fake.phone_number(),
                "email": random.choice([owner_email, fake.email()]),
                "website": fake.url(),
                "is_active": create_valid or random.choice([True, False]),
                "has_online_tax_account": create_valid or random.choice([True, False]),
                "ngohub_org_id": random.choice([random.randint(1, 9999), None]),
            }
            try:
                org = Ngo.objects.create(**organization_details)
                org.save()
            except IntegrityError:
                owner.delete()
                continue

            organizations.append(org)

            owner.ngo = org
            owner.save()

            ignore_cause = not create_valid or random.choice(range(0, 6)) == 3

            if ignore_cause:
                continue

            try:
                ngo_cause = Cause.objects.create(
                    ngo=org,
                    is_main=True,
                    allow_online_collection=org.has_online_tax_account and random.choice(range(0, 6)) == 3,
                    slug=kebab_case_name,
                    name=org_name,
                    description=fake.paragraph(nb_sentences=3, variable_nb_sentences=True),
                    bank_account=fake.iban(),
                )
                ngo_cause.save()
            except IntegrityError:
                consecutive_creation_errors += 1
                if consecutive_creation_errors > 10:
                    self.stdout.write(
                        self.style.ERROR("Too many consecutive creation errors. Aborting and writing to the database.")
                    )
                    break
                continue

            if len(organizations) % 100 == 0:
                self.stdout.write(self.style.SUCCESS(f"Created {len(organizations)} organization(s) so far..."))

        self.stdout.write(self.style.SUCCESS(f"Successfully created {len(organizations)} organization(s)."))
