# Generated by Django 4.2.9 on 2024-01-27 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django_cryptography.fields
import donations.models.main
import functools


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(blank=True, default="", max_length=100, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, default="", max_length=100, verbose_name="last name")),
                ("initial", models.CharField(blank=True, default="", max_length=5, verbose_name="initials")),
                (
                    "cnp",
                    django_cryptography.fields.encrypt(
                        models.CharField(blank=True, default="", max_length=13, verbose_name="CNP")
                    ),
                ),
                ("city", models.CharField(blank=True, db_index=True, default="", max_length=100, verbose_name="city")),
                (
                    "county",
                    models.CharField(blank=True, db_index=True, default="", max_length=100, verbose_name="county"),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30, verbose_name="telephone")),
                ("email", models.EmailField(db_index=True, max_length=254, verbose_name="email")),
                (
                    "is_anonymous",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="If the user would like the ngo to see the donation",
                        verbose_name="anonymous",
                    ),
                ),
                (
                    "income_type",
                    models.CharField(
                        blank=True,
                        choices=[("wage", "wage"), ("pension", "pension")],
                        default="wage",
                        max_length=30,
                        verbose_name="income type",
                    ),
                ),
                (
                    "two_years",
                    models.BooleanField(
                        default=False, help_text="If the user wants to donate for 2 years", verbose_name="two years"
                    ),
                ),
                ("geoip", models.JSONField(blank=True, default=dict, verbose_name="Geo IP")),
                ("pdf_url", models.URLField(blank=True, default="", max_length=255, verbose_name="PDF URL")),
                ("filename", models.CharField(blank=True, default="", max_length=100, verbose_name="filename")),
                ("has_signed", models.BooleanField(db_index=True, default=False, verbose_name="has signed")),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        upload_to=functools.partial(donations.models.main.year_ngo_donor_directory_path, *("documents",), **{}),
                        verbose_name="PDF file",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="date created")),
            ],
            options={
                "verbose_name": "donor",
                "verbose_name_plural": "donors",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("error", "Error"), ("done", "Done")],
                        db_index=True,
                        default="new",
                        max_length=5,
                        verbose_name="status",
                    ),
                ),
                ("url", models.URLField(blank=True, default="", max_length=255, verbose_name="URL")),
                ("date_created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="date created")),
            ],
        ),
        migrations.CreateModel(
            name="Ngo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100,
                        unique=True,
                        validators=[donations.models.main.ngo_slug_validator],
                        verbose_name="slug",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, verbose_name="Name")),
                ("description", models.TextField(verbose_name="description")),
                ("logo_url", models.URLField(blank=True, default="", verbose_name="logo url")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        storage=donations.models.main.select_public_storage,
                        upload_to=functools.partial(donations.models.main.ngo_directory_path, *("logos",), **{}),
                        verbose_name="logo",
                    ),
                ),
                ("image_url", models.URLField(blank=True, default="", verbose_name="image url")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        storage=donations.models.main.select_public_storage,
                        upload_to=functools.partial(donations.models.main.ngo_directory_path, *("images",), **{}),
                        verbose_name="image",
                    ),
                ),
                ("bank_account", models.CharField(max_length=100, verbose_name="bank account")),
                (
                    "registration_number",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        validators=[donations.models.main.ngo_id_number_validator],
                        verbose_name="registration number",
                    ),
                ),
                ("address", models.TextField(blank=True, default="", verbose_name="address")),
                (
                    "county",
                    models.CharField(blank=True, db_index=True, default="", max_length=100, verbose_name="county"),
                ),
                (
                    "active_region",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="active region"
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30, verbose_name="telephone")),
                (
                    "email",
                    models.EmailField(blank=True, db_index=True, default="", max_length=254, verbose_name="email"),
                ),
                ("website", models.URLField(blank=True, default="", verbose_name="website")),
                ("other_emails", models.TextField(blank=True, default="", verbose_name="other emails")),
                ("is_verified", models.BooleanField(db_index=True, default=False, verbose_name="is verified")),
                (
                    "has_special_status",
                    models.BooleanField(db_index=True, default=False, verbose_name="has special status"),
                ),
                (
                    "is_accepting_forms",
                    models.BooleanField(db_index=True, default=False, verbose_name="is accepting forms"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="is active")),
                ("form_url", models.URLField(blank=True, default="", max_length=255, verbose_name="form url")),
                (
                    "custom_form",
                    models.FileField(
                        blank=True,
                        storage=donations.models.main.select_public_storage,
                        upload_to=functools.partial(donations.models.main.ngo_directory_path, *("forms",), **{}),
                        verbose_name="form with ngo data",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="date created")),
                ("date_updated", models.DateTimeField(auto_now=True, db_index=True, verbose_name="date updated")),
            ],
            options={
                "verbose_name": "NGO",
                "verbose_name_plural": "NGOs",
            },
        ),
        migrations.AddConstraint(
            model_name="ngo",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("slug"), name="slug__unique"),
        ),
        migrations.AddField(
            model_name="job",
            name="ngo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="donations.ngo", verbose_name="NGO"
            ),
        ),
    ]
