# Generated by Django 4.2.9 on 2024-02-02 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="owner"
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="ngo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="donations.ngo", verbose_name="NGO"
            ),
        ),
    ]
