# Generated by Django 4.2.10 on 2024-02-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="url",
        ),
        migrations.AddField(
            model_name="job",
            name="date_finished",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date finished"),
        ),
        migrations.AddField(
            model_name="job",
            name="zip",
            field=models.FileField(blank=True, null=True, upload_to="donations", verbose_name="ZIP"),
        ),
    ]
