# Generated by Django 4.2.9 on 2024-01-30 06:46

from django.db import migrations, models
import donations.models.main
import functools


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                upload_to=functools.partial(donations.models.main.year_ngo_donor_directory_path, *("forms",), **{}),
                verbose_name="PDF file",
            ),
        ),
    ]
