# Generated by Django 4.2.9 on 2024-01-04 13:58

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0002_alter_ngo_form_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="initial",
            field=models.CharField(blank=True, default="", max_length=5, verbose_name="initials"),
        ),
        migrations.AddField(
            model_name="donor",
            name="personal_identifier",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, default="", max_length=13, verbose_name="CNP")
            ),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="form_url",
            field=models.CharField(blank=True, default="", max_length=255, unique=True, verbose_name="form url"),
        ),
    ]
