# Generated by Django 4.2.9 on 2024-01-08 12:23

from django.db import migrations, models
import donations.models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0003_donor_initial_donor_personal_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ngo",
            name="form_url",
        ),
        migrations.RemoveField(
            model_name="ngo",
            name="id",
        ),
        migrations.AddField(
            model_name="ngo",
            name="custom_form",
            field=models.FileField(blank=True, upload_to="custom_forms", verbose_name="custom form"),
        ),
        migrations.AddField(
            model_name="ngo",
            name="identifier",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[donations.models.ngo_identifier_validator],
                verbose_name="identifier",
            ),
            preserve_default=False,
        ),
    ]
