# Generated by Django 4.2.9 on 2024-01-31 08:25

from django.db import migrations, models
import donations.models.main
import functools


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0003_alter_donor_pdf_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ngo",
            name="custom_form",
        ),
        migrations.AddField(
            model_name="ngo",
            name="prefilled_form",
            field=models.FileField(
                blank=True,
                storage=donations.models.main.select_public_storage,
                upload_to=functools.partial(donations.models.main.ngo_directory_path, *("forms",), **{}),
                verbose_name="form with prefilled ngo data",
            ),
        ),
    ]
