# Generated by Django 4.2.9 on 2024-01-10 04:54

from django.db import migrations, models
import django.db.models.functions.text
import donations.models
import functools


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0003_donor_initial_donor_personal_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngo",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=donations.models.select_public_storage,
                upload_to=functools.partial(donations.models.ngo_directory_path, *("images",), **{}),
                verbose_name="image",
            ),
        ),
        migrations.AddField(
            model_name="ngo",
            name="logo",
            field=models.ImageField(
                blank=True,
                storage=donations.models.select_public_storage,
                upload_to=functools.partial(donations.models.ngo_directory_path, *("logos",), **{}),
                verbose_name="logo",
            ),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="form_url",
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name="form url"),
        ),
        migrations.AddConstraint(
            model_name="ngo",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("form_url"), name="form_url_unique"
            ),
        ),
    ]
