# Generated by Django 4.2.10 on 2024-02-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0003_alter_ngo_name_alter_ngo_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="date_created",
            field=models.DateTimeField(db_index=True, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="date_created",
            field=models.DateTimeField(db_index=True, verbose_name="date created"),
        ),
    ]
