# Generated by Django 4.2.9 on 2024-01-10 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0004_ngo_image_ngo_logo_alter_ngo_form_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donor",
            old_name="personal_identifier",
            new_name="cnp",
        ),
    ]
