# Generated by Django 4.2.9 on 2024-01-31 08:56

from django.db import migrations, models
import donations.models.main
import functools


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_remove_ngo_custom_form_ngo_prefilled_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngo",
            name="prefilled_form",
            field=models.FileField(
                blank=True,
                storage=donations.models.main.select_public_storage,
                upload_to=functools.partial(donations.models.main.ngo_directory_path, *("prefilled_forms",), **{}),
                verbose_name="form with prefilled ngo data",
            ),
        ),
    ]
