# Generated by Django 4.2.9 on 2024-01-11 05:34

from django.db import migrations, models
import donations.models
import functools


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0005_rename_personal_identifier_donor_cnp"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                upload_to=functools.partial(donations.models.year_directory_path, *("documents",), **{}),
                verbose_name="PDF file",
            ),
        ),
    ]
