# Generated by Django 4.2.9 on 2024-01-31 12:37

from django.db import migrations, models
import donations.models.main
import functools


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0005_alter_ngo_prefilled_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                upload_to=functools.partial(
                    donations.models.main.year_ngo_donor_directory_path, *("donation-forms",), **{}
                ),
                verbose_name="PDF file",
            ),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="prefilled_form",
            field=models.FileField(
                blank=True,
                storage=donations.models.main.select_public_storage,
                upload_to=functools.partial(donations.models.main.year_ngo_directory_path, *("ngo-forms",), **{}),
                verbose_name="form with prefilled ngo data",
            ),
        ),
    ]
