# Generated by Django 4.2.9 on 2024-01-11 11:38

from django.db import migrations, models
import django.db.models.functions.text
import donations.models
import functools


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0006_donor_pdf_file"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ngo",
            name="form_url_unique",
        ),
        migrations.AddField(
            model_name="ngo",
            name="custom_form",
            field=models.FileField(
                blank=True,
                storage=donations.models.select_public_storage,
                upload_to=functools.partial(donations.models.ngo_directory_path, *("forms",), **{}),
                verbose_name="form with ngo data",
            ),
        ),
        migrations.AddField(
            model_name="ngo",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name="date updated"),
        ),
        migrations.AddField(
            model_name="ngo",
            name="slug",
            field=models.SlugField(
                default="",
                max_length=100,
                unique=True,
                validators=[donations.models.ngo_identifier_validator],
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ngo",
            name="form_url",
            field=models.URLField(blank=True, default="", max_length=255, verbose_name="form url"),
        ),
        migrations.AddConstraint(
            model_name="ngo",
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower("slug"), name="slug__unique"),
        ),
    ]
