# Generated by Django 4.2.9 on 2024-02-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0007_donor_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="address",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="cnp",
        ),
        migrations.AddField(
            model_name="donor",
            name="encrypted_address",
            field=models.TextField(blank=True, default="", verbose_name="address"),
        ),
        migrations.AddField(
            model_name="donor",
            name="encrypted_cnp",
            field=models.TextField(blank=True, default="", verbose_name="CNP"),
        ),
    ]
