# Generated by Django 4.2.10 on 2024-02-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0008_alter_job_options_alter_job_ngo_alter_job_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="date_created",
            field=models.DateTimeField(db_index=True, verbose_name="date created"),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="date_created",
            field=models.DateTimeField(db_index=True, verbose_name="date created"),
        ),
    ]
