# Generated by Django 5.1.2 on 2024-10-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0013_rename_has_special_status_ngo_is_social_service_viable_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donor",
            old_name="first_name",
            new_name="l_name",
        ),
    ]
