# Generated by Django 5.1.2 on 2024-10-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0014_rename_first_name_donor_l_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donor",
            old_name="last_name",
            new_name="f_name",
        ),
    ]
