# Generated by Django 5.1.4 on 2025-01-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0016_remove_donor_pdf_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="anaf_gdpr",
            field=models.BooleanField(
                default=False,
                help_text="If the user agrees for ANAF to share their data with the NGO",
                verbose_name="ANAF GDPR",
            ),
        ),
    ]
