# Generated by Django 5.1.4 on 2025-01-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0017_donor_anaf_gdpr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngo",
            name="is_accepting_forms",
            field=models.BooleanField(db_index=True, default=True, verbose_name="is accepting forms"),
        ),
    ]
