# Generated by Django 5.1.5 on 2025-01-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0020_ngo_display_email_ngo_display_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngo",
            name="locality",
            field=models.CharField(blank=True, db_index=True, default="", max_length=100, verbose_name="locality"),
        ),
    ]
