# Generated by Django 5.1.6 on 2025-02-14 10:46

import django.db.models.deletion
import donations.models.ngos
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0021_ngo_locality"),
    ]

    operations = [
        migrations.CreateModel(
            name="NgoForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allow_online_collection", models.BooleanField(default=False, verbose_name="allow online collection")),
                (
                    "display_image",
                    models.ImageField(
                        blank=True,
                        storage=donations.models.ngos.select_public_storage,
                        upload_to=functools.partial(donations.models.ngos.ngo_directory_path, *("logos",), **{}),
                        verbose_name="logo",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=150,
                        unique=True,
                        validators=[donations.models.ngos.ngo_slug_validator],
                        verbose_name="slug",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=200, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                ("bank_account", models.CharField(max_length=100, verbose_name="bank account")),
                ("date_created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="date created")),
                ("date_updated", models.DateTimeField(auto_now=True, db_index=True, verbose_name="date updated")),
                (
                    "ngo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="forms", to="donations.ngo"
                    ),
                ),
            ],
            options={
                "verbose_name": "NGO form",
                "verbose_name_plural": "NGO forms",
            },
        ),
    ]
