# Generated by Django 5.1.6 on 2025-02-18 11:06
import logging

from django.db import IntegrityError, migrations, transaction

logger = logging.getLogger(__name__)


def copy_ngos_to_causes(apps, _):
    Cause = apps.get_model("donations", "Cause")
    Ngo = apps.get_model("donations", "Ngo")

    for ngo in Ngo.objects.all():
        if ngo.causes.exists():
            continue

        cause = Cause(
            ngo=ngo,
            allow_online_collection=ngo.is_accepting_forms,
            display_image=ngo.logo,
            slug=ngo.slug,
            name=ngo.name,
            description=ngo.description,
            bank_account=ngo.bank_account,
        )

        try:
            cause.save()
        except IntegrityError as e:
            logger.warning("Could not save cause for NGO %s. ERROR: %s", ngo, e)


def copy_causes_to_ngos(apps, _):
    Cause = apps.get_model("donations", "Cause")
    Ngo = apps.get_model("donations", "Ngo")

    for ngo in Ngo.objects.filter(causes__isnull=False):
        # get the oldest form of the NGO
        cause: Cause = ngo.causes.order_by("date_created").first()
        ngo.logo = cause.display_image
        ngo.slug = cause.slug
        ngo.description = cause.description
        ngo.bank_account = cause.bank_account

        with transaction.atomic():
            ngo.save()
            ngo.causes.all().delete()


def add_cause_to_donors(apps, _):
    Cause = apps.get_model("donations", "Cause")
    Donor = apps.get_model("donations", "Donor")

    for donor in Donor.objects.all():
        cause: Cause = donor.ngo.causes.first()

        donor.cause = cause
        donor.save()


def add_cause_to_jobs(apps, _):
    Cause = apps.get_model("donations", "Cause")
    Job = apps.get_model("donations", "Job")

    for job in Job.objects.all():
        cause: Cause = job.ngo.causes.first()

        job.cause = cause
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0022_cause_donor_cause_job_cause"),
    ]

    operations = [
        migrations.RunPython(copy_ngos_to_causes, reverse_code=copy_causes_to_ngos),
        migrations.RunPython(add_cause_to_donors, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(add_cause_to_jobs, reverse_code=migrations.RunPython.noop),
    ]
