# Generated by Django 5.1.6 on 2025-02-14 10:47

from django.db import migrations


def move_forms_data(apps, _):
    NgoForm = apps.get_model("donations", "NgoForm")
    Ngo = apps.get_model("donations", "Ngo")

    for ngo in Ngo.objects.all():
        ngo_form = NgoForm(
            ngo=ngo,
            allow_online_collection=ngo.is_accepting_forms,
            display_image=ngo.logo,
            slug=ngo.slug,
            title=ngo.name,
            description=ngo.description,
            bank_account=ngo.bank_account,
        )

        ngo_form.save()


def move_forms_data_reverse(apps, _):
    NgoForm = apps.get_model("donations", "NgoForm")
    Ngo = apps.get_model("donations", "Ngo")

    for ngo in Ngo.objects.filter(forms__isnull=False):
        # get the oldest form of the NGO
        ngo_form: NgoForm = ngo.forms.order_by("created_at").first()

        ngo.logo = ngo_form.display_image
        ngo.slug = ngo_form.slug
        ngo.description = ngo_form.description
        ngo.bank_account = ngo_form.bank_account

        ngo.save()

        ngo.forms.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0022_ngoform"),
    ]

    operations = [
        migrations.RunPython(move_forms_data, reverse_code=move_forms_data_reverse),
    ]
