# Generated by Django 5.1.6 on 2025-03-04 09:22

import donations.models.ngos
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0023_auto_20250218_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cause",
            name="prefilled_form",
            field=models.FileField(
                blank=True,
                storage=donations.models.ngos.select_public_storage,
                upload_to=functools.partial(donations.models.ngos.year_cause_directory_path, *("ngo-forms",), **{}),
                verbose_name="form with prefilled cause",
            ),
        ),
    ]
