# Generated by Django 5.1.7 on 2025-03-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0025_alter_donor_f_name_alter_donor_l_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="number_of_donations",
            field=models.IntegerField(default=-1, verbose_name="donations count"),
        ),
    ]
