# Generated by Django 5.1.7 on 2025-03-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0026_job_number_of_donations"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="is_available",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="If the donation is available on the platform (not removed)",
                verbose_name="is available",
            ),
        ),
    ]
