# Generated by Django 5.1.7 on 2025-03-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0027_donor_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="cause",
            name="is_main",
            field=models.BooleanField(db_index=True, default=True, verbose_name="is main cause"),
        ),
        migrations.AddConstraint(
            model_name="cause",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)), fields=("ngo",), name="ngo_main_cause_unique"
            ),
        ),
    ]
