# Generated by Django 5.1.7 on 2025-03-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0028_cause_is_main_cause_ngo_main_cause_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="cause",
            name="visibility",
            field=models.CharField(
                choices=[("pub", "public"), ("unl", "unlisted"), ("pri", "private")],
                db_index=True,
                default="pub",
                max_length=3,
                verbose_name="form visibility",
            ),
        ),
    ]
