# Generated by Django 5.1.7 on 2025-04-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0029_cause_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cause",
            name="is_main",
            field=models.BooleanField(db_index=True, default=False, verbose_name="is main cause"),
        ),
    ]
