# Generated by Django 5.1.7 on 2025-03-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0029_cause_form_visibility"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cause",
            old_name="form_visibility",
            new_name="visibility",
        ),
    ]
