# Generated by Django 5.1.7 on 2025-04-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0030_alter_cause_is_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="cause",
            name="allow_online_notifications",
            field=models.BooleanField(default=False, verbose_name="allow online notifications"),
        ),
        migrations.AddField(
            model_name="cause",
            name="notifications_email",
            field=models.EmailField(blank=True, default="", max_length=254, verbose_name="notifications email"),
        ),
    ]
