# Generated by Django 5.1.7 on 2025-04-04 13:07

from django.db import migrations


def initialize_notifications_email(apps, schema_editor):
    Cause = apps.get_model("donations", "Cause")
    batch = []
    for cause in Cause.objects.filter(ngo__is_accepting_forms=True, notifications_email="").select_related("ngo"):
        cause.notifications_email = cause.ngo.email
        cause.allow_online_notifications = True
        batch.append(cause)
    Cause.objects.bulk_update(batch, ["notifications_email", "allow_online_notifications"])


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0031_cause_allow_online_notifications_and_more"),
    ]

    operations = [
        migrations.RunPython(initialize_notifications_email),
    ]
