# Generated by Django 5.1.8 on 2025-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0033_auto_20250409_1226"),
    ]

    operations = [
        migrations.AddField(
            model_name="cause",
            name="filename_cache",
            field=models.JSONField(default=dict, editable=False, verbose_name="Filename cache"),
        ),
    ]
