# Generated by Django 5.1.8 on 2025-04-16 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0034_cause_filename_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnFormsUpload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bank_account", models.CharField(max_length=24, verbose_name="IBAN")),
                ("uploaded_data", models.FileField(upload_to="own-forms/%Y/%m/%d/", verbose_name="uploaded data")),
                (
                    "result_data",
                    models.FileField(
                        blank=True, null=True, upload_to="own-forms/%Y/%m/%d/", verbose_name="result data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "public"),
                            ("vali", "validating uploaded data"),
                            ("pend", "awaiting processing"),
                            ("proc", "processing"),
                            ("fail", "failed"),
                            ("succ", "success"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=4,
                        verbose_name="status",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="date created")),
                ("date_updated", models.DateTimeField(auto_now=True, db_index=True, verbose_name="date updated")),
                (
                    "ngo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="own_forms_uploads",
                        to="donations.ngo",
                    ),
                ),
            ],
            options={
                "verbose_name": "bring your own forms upload",
                "verbose_name_plural": "bring your own forms uploads",
            },
        ),
    ]
