# Generated by Django 5.1.8 on 2025-04-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0034_cause_filename_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngo",
            name="bank_account",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="bank account"),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=150, verbose_name="slug"),
        ),
    ]
