# Generated by Django 5.1.8 on 2025-04-25 08:06

import django.core.validators
import django.db.models.deletion
import donations.models.byof
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0034_cause_filename_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnFormsUpload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bank_account", models.CharField(max_length=24, verbose_name="IBAN")),
                (
                    "uploaded_data",
                    models.FileField(
                        upload_to="own-forms/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(allowed_extensions=("csv",)),
                            donations.models.byof.MaxFileSizeValidator(2097152),
                        ],
                        verbose_name="uploaded data",
                    ),
                ),
                ("items_count", models.PositiveBigIntegerField(default=0, verbose_name="form count")),
                (
                    "result_data",
                    models.FileField(
                        blank=True, null=True, upload_to="own-forms/%Y/%m/%d/", verbose_name="result data"
                    ),
                ),
                ("result_text", models.TextField(blank=True, default="", null=True, verbose_name="result text")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "newly uploaded"),
                            ("vali", "validating uploaded data"),
                            ("proc", "processing"),
                            ("fail", "failed"),
                            ("succ", "success"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=4,
                        verbose_name="status",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="date created")),
                ("date_updated", models.DateTimeField(auto_now=True, db_index=True, verbose_name="date updated")),
                (
                    "ngo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="own_forms_uploads",
                        to="donations.ngo",
                    ),
                ),
            ],
            options={
                "verbose_name": "bring your own forms upload",
                "verbose_name_plural": "bring your own forms uploads",
            },
        ),
        migrations.CreateModel(
            name="RedirectionsDownloadJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("error", "Error"), ("done", "Done")],
                        db_index=True,
                        default="new",
                        max_length=5,
                        verbose_name="status",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="date created")),
                (
                    "date_finished",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date finished"),
                ),
                ("queryset", models.JSONField(verbose_name="queryset")),
                ("output_rows", models.IntegerField(default=-1, verbose_name="rows count")),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="donation-downloads/%Y/%m/%d/", verbose_name="output file"
                    ),
                ),
                (
                    "ngo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_jobs",
                        to="donations.ngo",
                        verbose_name="NGO",
                    ),
                ),
            ],
            options={
                "verbose_name": "download job",
                "verbose_name_plural": "download jobs",
                "ordering": ["-date_created"],
                "get_latest_by": "date_created",
            },
        ),
    ]
