# Generated by Django 5.1.8 on 2025-04-23 03:46

import django.core.validators
import donations.models.byof
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0035_ownformsupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownformsupload",
            name="uploaded_data",
            field=models.FileField(
                upload_to="own-forms/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=("csv",)),
                    donations.models.byof.MaxFileSizeValidator(2097152),
                ],
                verbose_name="uploaded data",
            ),
        ),
    ]
