# Generated by Django 5.2.1 on 2025-06-03 08:12

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0036_ownformsupload_redirectionsdownloadjob"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ngo",
            name="slug__unique",
        ),
        migrations.RemoveField(
            model_name="ngo",
            name="bank_account",
        ),
        migrations.RemoveField(
            model_name="ngo",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ngo",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="ngo",
            name="prefilled_form",
        ),
        migrations.RemoveField(
            model_name="ngo",
            name="slug",
        ),
        migrations.AlterField(
            model_name="ngo",
            name="name",
            field=models.CharField(db_index=True, max_length=200, verbose_name="Legal name"),
        ),
        migrations.AddConstraint(
            model_name="ngo",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("registration_number"), name="registration_number__unique"
            ),
        ),
    ]
