# Generated by Django 5.2.9 on 2025-12-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0037_remove_ngo_slug__unique_remove_ngo_bank_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngo",
            name="active_region",
            field=models.TextField(blank=True, default="", verbose_name="active region"),
        ),
    ]
