# Generated by Django 5.1.8 on 2025-04-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0038_alter_ownformsupload_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownformsupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "newly uploaded"),
                    ("vali", "validating uploaded data"),
                    ("proc", "processing"),
                    ("fail", "failed"),
                    ("succ", "success"),
                ],
                db_index=True,
                default="new",
                max_length=4,
                verbose_name="status",
            ),
        ),
    ]
