# Generated by Django 5.2.9 on 2025-12-17 08:05

from django.db import migrations
from django.db.transaction import atomic


def set_has_online_tax_account(apps, _):
    Cause = apps.get_model("donations", "Cause")
    ngo_ids_with_causes_that_allow_online_collection: list[int] = (
        Cause.objects.filter(allow_online_collection=True).values_list("ngo_id", flat=True).distinct()
    )

    Ngo = apps.get_model("donations", "Ngo")

    with atomic():
        Ngo.objects.filter(
            id__in=ngo_ids_with_causes_that_allow_online_collection,
        ).update(has_online_tax_account=True)

    with atomic():
        Ngo.objects.exclude(
            id__in=ngo_ids_with_causes_that_allow_online_collection,
        ).update(has_online_tax_account=False)


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0039_ngo_has_online_tax_account"),
    ]

    operations = [
        migrations.RunPython(set_has_online_tax_account, reverse_code=migrations.RunPython.noop),
    ]
