# Generated by Django 5.1.8 on 2025-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0039_alter_ownformsupload_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownformsupload",
            name="items_count",
            field=models.PositiveBigIntegerField(default=0, verbose_name="form count"),
        ),
    ]
