# Generated by Django 5.2.10 on 2026-01-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0040_auto_20251217_1005"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="personal_data_removal_started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="date personal data removal started"),
        ),
        migrations.AddField(
            model_name="donor",
            name="personal_data_removed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="date personal data removed"),
        ),
    ]
