# Generated by Django 5.2.12 on 2026-03-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0041_donor_personal_data_removal_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='acknowledge_missing_cult_registry',
            field=models.BooleanField(default=False, verbose_name='acknowledge missing ANAF Cult Registry info'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='cult_registry_check_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last check in the ANAF Cult Registry'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='is_in_cult_registry',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='presence in the ANAF Cult Registry'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='pause_cult_registry_check',
            field=models.BooleanField(default=False, verbose_name='pause checking the ANAF Cult Registry'),
        ),
    ]
