# Generated by Django 5.2.12 on 2026-03-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0042_ngo_acknowledge_missing_cult_registry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='cult_registry_check_date',
            new_name='cult_registry_check_started',
        ),
    ]
