# Generated by Django 5.2.12 on 2026-03-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0043_rename_cult_registry_check_date_ngo_cult_registry_check_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='cult_registry_check_ended',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last completed check in the ANAF Cult Registry'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='cult_registry_check_started',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last started check in the ANAF Cult Registry'),
        ),
    ]
