# Generated by Django 5.2.12 on 2026-03-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0044_ngo_cult_registry_check_ended_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'get_latest_by': 'date_created', 'ordering': ('-date_created',), 'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterModelOptions(
            name='redirectionsdownloadjob',
            options={'get_latest_by': 'date_created', 'ordering': ('-date_created',), 'verbose_name': 'download job', 'verbose_name_plural': 'download jobs'},
        ),
    ]
