# Generated by Django 5.2.12 on 2026-04-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0045_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='became_absent_from_cult_registry',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='became absent from the ANAF Cult Registry'),
        ),
    ]
