# Generated by Django 5.2.12 on 2026-04-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0046_ngo_became_absent_from_cult_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='cult_registry_check_started',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='last started check in the ANAF Cult Registry'),
        ),
    ]
