# Generated by Django 5.2.12 on 2026-04-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0047_alter_ngo_cult_registry_check_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='became_absent_from_cult_registry',
            field=models.BooleanField(default=False, editable=False, verbose_name='became absent from the ANAF Cult Registry'),
        ),
    ]
