# Generated by Django 5.2.12 on 2026-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0048_alter_ngo_became_absent_from_cult_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='registration_number_valid',
            field=models.BooleanField(db_index=True, null=True, verbose_name='the registration number is valid'),
        ),
    ]
