"""empty message

Revision ID: 521102d4d595
Revises: 
Create Date: 2019-03-10 18:22:19.925141

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '521102d4d595'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngo_entity_tag',
                    sa.Column('tag_id', sa.Integer(), nullable=True),
                    sa.Column('ngoentity_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['ngoentity_id'], ['ngo_entity.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
                    )
    op.drop_table('ngoentity_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngoentity_tag',
                    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('ngoentity_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['ngoentity_id'], ['ngo_entity.id'],
                                            name='ngoentity_tag_ngoentity_id_fkey'),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='ngoentity_tag_tag_id_fkey')
                    )
    op.drop_table('ngo_entity_tag')
    # ### end Alembic commands ###
