# Generated by Django 4.2.9 on 2024-01-27 08:54

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, db_index=True, max_length=100, verbose_name="name")),
                ("subdomain", models.CharField(max_length=100, unique=True, verbose_name="subdomain")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="is active")),
                ("ngos", models.ManyToManyField(blank=True, to="donations.ngo", verbose_name="NGOs")),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
        migrations.AddConstraint(
            model_name="partner",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("subdomain"), name="subdomain_unique"
            ),
        ),
    ]
