# Generated by Django 4.2.8 on 2023-12-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="ngos",
            field=models.ManyToManyField(blank=True, to="donations.ngo", verbose_name="NGOs"),
        ),
    ]
