# Generated by Django 4.2.10 on 2024-02-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_initial"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="ngos",
            field=models.ManyToManyField(blank=True, related_name="partners", to="donations.ngo", verbose_name="NGOs"),
        ),
    ]
