# Generated by Django 4.2.9 on 2024-01-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="has_custom_header",
            field=models.BooleanField(default=False, verbose_name="has custom header"),
        ),
        migrations.AddField(
            model_name="partner",
            name="has_custom_note",
            field=models.BooleanField(default=False, verbose_name="has custom note"),
        ),
    ]
