# Generated by Django 4.2.11 on 2024-03-25 09:34

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0002_alter_partner_ngos"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="display_ordering",
            field=models.CharField(
                choices=[("ABC", "Alphabetical"), ("AGE", "Newest"), ("RND", "Random")],
                default="RND",
                max_length=3,
                verbose_name="display ordering",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="subdomain",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[utils.validators.url_validator],
                verbose_name="subdomain",
            ),
        ),
    ]
