# Generated by Django 5.1.5 on 2025-02-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0021_ngo_locality"),
        ("partners", "0003_partner_display_ordering_alter_partner_subdomain"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerNgo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_order", models.PositiveIntegerField(default=0, verbose_name="display order")),
                (
                    "ngo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_ngos",
                        to="donations.ngo",
                        verbose_name="NGO",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_ngos",
                        to="partners.partner",
                        verbose_name="partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner NGO",
                "verbose_name_plural": "Partner NGOs",
                "constraints": [models.UniqueConstraint(fields=("partner", "ngo"), name="partner_ngo_unique")],
            },
        ),
    ]
