# Generated by Django 5.1.5 on 2025-02-11 11:17

from django.db import migrations


def create_through_relations(apps, _):
    Partner = apps.get_model("partners", "Partner")
    PartnerNgo = apps.get_model("partners", "PartnerNgo")

    for partner in Partner.objects.all():
        for ngo in partner.ngos.all():
            PartnerNgo(
                ngo=ngo,
                partner=partner,
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_partnerngo"),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
