# Generated by Django 5.1.5 on 2025-02-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0005_auto_20250211_1317"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="ngos",
        ),
    ]
