# Generated by Django 5.1.5 on 2025-02-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0021_ngo_locality"),
        ("partners", "0006_remove_partner_ngos"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="ngos",
            field=models.ManyToManyField(
                blank=True,
                related_name="partners",
                through="partners.PartnerNgo",
                to="donations.ngo",
                verbose_name="NGOs",
            ),
        ),
    ]
