# Generated by Django 5.1.5 on 2025-02-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0007_partner_ngos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="display_ordering",
            field=models.CharField(
                choices=[
                    ("CST", "Custom"),
                    ("ABC", "Alphabetical"),
                    ("CBA", "Alphabetical (reverse)"),
                    ("AGE", "Newest"),
                    ("OLD", "Oldest"),
                    ("RND", "Random"),
                ],
                default="RND",
                max_length=3,
                verbose_name="display ordering",
            ),
        ),
    ]
