# Generated by Django 5.1.6 on 2025-02-19 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0023_auto_20250218_1306"),
        ("partners", "0008_alter_partner_display_ordering"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerCause",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_order", models.PositiveIntegerField(default=0, verbose_name="display order")),
                (
                    "cause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_causes",
                        to="donations.cause",
                        verbose_name="Cause",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_causes",
                        to="partners.partner",
                        verbose_name="partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Cause",
                "verbose_name_plural": "Partner Causes",
            },
        ),
        migrations.AddField(
            model_name="partner",
            name="causes",
            field=models.ManyToManyField(
                blank=True,
                related_name="partners",
                through="partners.PartnerCause",
                to="donations.cause",
                verbose_name="Causes",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnercause",
            constraint=models.UniqueConstraint(fields=("partner", "cause"), name="partner_cause_unique"),
        ),
    ]
