# Generated by Django 5.1.6 on 2025-02-19 17:00
import logging

from django.db import IntegrityError, migrations

logger = logging.getLogger(__name__)


def copy_partner_ngo_to_partner_cause(apps, _):
    Cause = apps.get_model("donations", "Cause")
    Ngo = apps.get_model("donations", "Ngo")

    Partner = apps.get_model("partners", "Partner")
    PartnerCause = apps.get_model("partners", "PartnerCause")
    PartnerNgo = apps.get_model("partners", "PartnerNgo")

    for partner in Partner.objects.all():
        for partner_ngo in PartnerNgo.objects.filter(partner=partner):
            ngo: Ngo = partner_ngo.ngo
            ngo_cause: Cause = Cause.objects.filter(ngo=ngo).first()

            if not ngo_cause:
                logger.warning("Could not find cause for NGO %s", ngo)
                continue

            partner_cause = PartnerCause(
                partner=partner,
                cause=ngo_cause,
                display_order=partner_ngo.display_order,
            )

            try:
                partner_cause.save()
            except IntegrityError as e:
                logger.warning("Could not save cause for NGO %s. ERROR: %s", ngo, e)


def copy_partner_cause_to_partner_ngo(apps, _):
    Cause = apps.get_model("donations", "Cause")
    Ngo = apps.get_model("donations", "Ngo")

    Partner = apps.get_model("partners", "Partner")
    PartnerCause = apps.get_model("partners", "PartnerCause")
    PartnerNgo = apps.get_model("partners", "PartnerNgo")

    for partner in Partner.objects.all():
        for partner_cause in PartnerCause.objects.filter(partner=partner):
            cause: Cause = partner_cause.cause
            ngo: Ngo = cause.ngo

            try:
                PartnerNgo.objects.get_or_create(
                    partner=partner,
                    ngo=ngo,
                    display_order=partner_cause.display_order,
                )
            except IntegrityError as e:
                logger.warning("Could not save cause for NGO %s. ERROR: %s", ngo, e)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("partners", "0009_partnercause_partner_causes_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_partner_ngo_to_partner_cause, reverse_code=copy_partner_cause_to_partner_ngo),
    ]
