# Generated by Django 5.1.8 on 2025-05-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0010_auto_20250219_1900"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="custom_cta",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom call-to-action for the partner, if empty, the default call-to-action will be used.",
                max_length=50,
                verbose_name="custom call-to-action",
            ),
        ),
    ]
