# Generated by Django 5.1.8 on 2025-05-12 11:08

from django.db import migrations


def set_default_cta(apps, _):
    Partner = apps.get_model("partners", "Partner")

    partners_with_custom_note = Partner.objects.filter(has_custom_note=True)
    partners_with_custom_note.update(custom_cta="către un ONG la alegere")


def set_custom_note(apps, _):
    Partner = apps.get_model("partners", "Partner")

    partners_with_custom_note = Partner.objects.exclude(custom_cta="")
    partners_with_custom_note.update(has_custom_note=True)


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0011_partner_custom_cta"),
    ]

    operations = [
        migrations.RunPython(set_default_cta, reverse_code=set_custom_note),
    ]
