# Generated by Django 4.2.10 on 2024-02-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "import_type",
                    models.CharField(
                        choices=[("users.User", "User"), ("donations.Ngo", "Ngo"), ("donations.Donor", "Donor")],
                        max_length=32,
                        verbose_name="Import type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("working", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("has_header", models.BooleanField(default=True, verbose_name="Has header")),
                ("csv_file", models.FileField(upload_to="imports/", verbose_name="File")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, verbose_name="Uploaded at")),
            ],
            options={
                "verbose_name": "Import",
                "verbose_name_plural": "Imports",
            },
        ),
    ]
