# Generated by Django 5.1.2 on 2024-10-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0003_alter_importjob_csv_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importjob",
            options={},
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="csv_file",
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="has_header",
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="import_type",
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="status",
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="uploaded_at",
        ),
    ]
