# Generated by Django 5.1.2 on 2024-10-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0004_alter_importjob_options_remove_importjob_csv_file_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImportJob",
        ),
    ]
