# Generated by Django 4.2.10 on 2024-02-14 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="date created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="date updated"),
        ),
    ]
