# Generated by Django 4.2.8 on 2023-12-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validation token timestamp'),
        ),
        migrations.AddField(
            model_name='user',
            name='validation_token',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='validation token'),
        ),
    ]
