# Generated by Django 4.2.10 on 2024-02-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_date_created_user_date_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_created",
            field=models.DateTimeField(verbose_name="date created"),
        ),
    ]
