# Generated by Django 4.2.8 on 2023-12-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_user_token_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', editable=False, help_text='We do not use this field', max_length=150, verbose_name='username'),
        ),
    ]
