# Generated by Django 4.2.10 on 2024-02-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_date_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": (("can_view_old_dashboard", "Can view the old dashboard"),)},
        ),
    ]
