# Generated by Django 4.2.13 on 2024-08-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_groupproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_ngohub_user",
            field=models.BooleanField(default=False),
        ),
    ]
