# Generated by Django 5.1.5 on 2025-02-11 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0008_alter_partner_display_ordering"),
        ("users", "0009_user_is_ngohub_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="partners.partner",
                verbose_name="Partner",
            ),
        ),
    ]
