# Generated by Django 5.1.5 on 2025-01-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_is_ngohub_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="old_password",
        ),
    ]
