# Generated by Django 5.1.6 on 2025-02-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_ngohub_user",
            field=models.BooleanField(db_index=True, default=False, verbose_name="is ngohub user"),
        ),
    ]
