# Generated by Django 5.2.11 on 2026-03-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_is_ngohub_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_old_dashboard', 'Can view the old dashboard'), ('can_reset_staging', 'Can reset the staging environment'))},
        ),
    ]
