# Generated by Django 5.2.7 on 2025-11-03 11:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=100, verbose_name="name")),
                ("date", models.DateField(blank=True, db_index=True, null=True, verbose_name="date")),
                (
                    "value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name="value"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="expires at")),
            ],
            options={
                "verbose_name": "statistic",
                "verbose_name_plural": "statistics",
                "ordering": ["-date", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"), models.F("date"), name="unique_stat_name_date"
                    )
                ],
            },
        ),
    ]
