# Generated by Django 5.2.12 on 2026-03-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ('-date', 'name'), 'verbose_name': 'statistic', 'verbose_name_plural': 'statistics'},
        ),
    ]
