"""
Django settings for the redirectioneaza project.

Initially generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from .app_configs import *
from .auth import *
from .base import *
from .cache import *
from .captcha_analytics import *
from .constants import *
from .database import *
from .django_q import *
from .email import *
from .environment import *
from .feature_flags import *
from .i18n import *
from .logging import *
from .storages import *
from .templates import *
from .unfold import *
