from .base import DEBUG
from .environment import env

# reCAPTCHA & Analytics settings

GOOGLE_ANALYTICS_ID = env.str("GOOGLE_ANALYTICS_ID")

RECAPTCHA_PUBLIC_KEY = env.str("CAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = env.str("CAPTCHA_PRIVATE_KEY")
RECAPTCHA_REQUIRED_SCORE = env.float("CAPTCHA_REQUIRED_SCORE")

RECAPTCHA_VERIFY_URL = env.str("CAPTCHA_VERIFY_URL")
RECAPTCHA_POST_PARAM = env.str("CAPTCHA_POST_PARAM")

RECAPTCHA_ENABLED = env.bool("RECAPTCHA_ENABLED", True if RECAPTCHA_PUBLIC_KEY else False)

if DEBUG or not RECAPTCHA_ENABLED:
    SILENCED_SYSTEM_CHECKS = ["django_recaptcha.recaptcha_test_key_error"]
