from .base import DEBUG
from .environment import env

# Feature flags
ENABLE_FLAG_CONTACT = env.bool("ENABLE_FLAG_CONTACT", False)
ENABLE_MULTIPLE_FORMS = env.bool("ENABLE_MULTIPLE_FORMS", True)
ENABLE_BYOF = env.bool("ENABLE_BYOF", False)
ENABLE_CSV_DOWNLOAD = env.bool("ENABLE_CSV_DOWNLOAD", False)

# Configurations for the NGO Hub integration
UPDATE_ORGANIZATION_METHOD = env("UPDATE_ORGANIZATION_METHOD")

# Legal data full validation settings
ENABLE_FULL_VALIDATION_CUI = env.bool("ENABLE_FULL_VALIDATION_CUI")
ENABLE_FULL_VALIDATION_IBAN = env.bool("ENABLE_FULL_VALIDATION_IBAN")
ENABLE_FULL_VALIDATION_PHONE = env.bool("ENABLE_FULL_VALIDATION_PHONE")
ENABLE_FULL_VALIDATION_CNP = env.bool("ENABLE_FULL_VALIDATION_CNP")

# Form download settings
ENABLE_FORMS_DOWNLOAD = env.bool("ENABLE_FORMS_DOWNLOAD", True)
TIMEDELTA_FORMS_DOWNLOAD_MINUTES = env.int("TIMEDELTA_FORMS_DOWNLOAD_MINUTES")

FORCE_PARTNER = False
if DEBUG:
    FORCE_PARTNER = env.bool("FORCE_PARTNER", False)
