from .environment import env

ANAF_CULT_REGISTRY_BATCH_SIZE = 100
ANAF_CULT_REGISTRY_ENDPOINT = "https://webservicesp.anaf.ro/RegCult/api/v2/ws/cult"
ANAF_CULT_REGISTRY_EXISTING_RECHECK_DAYS = 120
ANAF_CULT_REGISTRY_MISSING_RECHECK_DAYS = 30
ANAF_CULT_REGISTRY_SCHEDULE_SECONDS = 180
ENABLE_ANAF_CULT_REGISTRY = env.bool("ENABLE_CULT_REGISTRY_CHECK", True)
